# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Jey Zhang
subtitle: Life is Now.
description: Life is Now.
author: Jey Zhang
email: zhangjieup@gmail.com
language: en
timezone: PRC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.jeyzhang.com
root: /
permalink: :title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    github: git@github.com:JeyZhang/jeyzhang.github.io.git
    gitcafe: git@gitcafe.com:JeyZhang/JeyZhang.git,gitcafe-pages
	
# Comment plug-in
disqus_shortname: jeyzhang
  
# Menu
menu:
  home: /
  archives: /archives
  tags: /tags
  
# Avatar
avatar: /upload/image/avatar.png

# Social links
social:
  facebook: http://www.facebook.com/jeyzhang
  weibo: http://weibo.com/jerrychang0402
  zhihu: http://www.zhihu.com/people/zhangjieup
  github: https://github.com/jeyzhang

# Friendly Links
links_title: Links
# Links
links:
  Tong: http://www.yunaitong.cn
  
# analytics
google_analytics: UA-71292341-1
baidu_analytics: eed1a5ff91ce000d3cbee31156f82f2c

# JiaThis Share
jiathis: true

# Swiftype Search Key
swiftype_key: LwCA4Pqyomh6kHjA4fV9

# 首页显示篇数
index_generator:
  per_page: 5

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10
  
# sitemap
sitemap:
path: sitemap.xml
baidusitemap:
path: baidusitemap.xml

# equation plugins
plugins: 
  hexo-math
  
# add post views
leancloud_visitors:
  enable: true
  app_id: 4KyzRuAgl6zwWXQK1UfxmIh0-gzGzoHsz
  app_key: YeXrCFBwTG1qRdqS2rUJ7XgJ

